language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"  # 3.7 development branch
env:
  - COVERAGE_VERSION=5
  - COVERAGE_VERSION=4
  - COVERAGE_VERSION=3
  - IPYTHON_VERSION=7
  - IPYTHON_VERSION=6
install:
  - pip install -q coverage~=$COVERAGE_VERSION ipython~=$IPYTHON_VERSION
script:
  - python setup.py tests
