language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - COVERAGE_VERSION=4.0 IPYTHON_VERSION=7.0
  - COVERAGE_VERSION=4.0 IPYTHON_VERSION=6.0
  - COVERAGE_VERSION=4.0 IPYTHON_VERSION=5.0
  - COVERAGE_VERSION=4.0 IPYTHON_VERSION=4.0
  - COVERAGE_VERSION=4.0 IPYTHON_VERSION=3.0
  - COVERAGE_VERSION=4.0 IPYTHON_VERSION=2.0
  - COVERAGE_VERSION=4.0 IPYTHON_VERSION=1.0
  - COVERAGE_VERSION=3.0 IPYTHON_VERSION=7.0
  - COVERAGE_VERSION=2.0 IPYTHON_VERSION=7.0
  - COVERAGE_VERSION=1.0 IPYTHON_VERSION=7.0
install:
  - pip install --upgrade pip
  - pip install -q coverage~=$COVERAGE_VERSION ipython~=$IPYTHON_VERSION
script:
  - python setup.py test
